version: 2

project_name: traforato

before:
  hooks:
    - go mod download

builds:
  - id: controller
    main: ./cmd/controller
    binary: traforato-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

  - id: worker
    main: ./cmd/worker
    binary: traforato-worker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: controller
    ids:
      - controller
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: worker
    ids:
      - worker
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  prerelease: auto
